### ISSUE TITLE
Result.catchAndWrapSync hides the actual Error

### ISSUE THREAD

**Issue by auwtch** [hazae41/result#1]
Code:
```ts
import { Result } from '@hazae41/result';

Result.catchAndWrapSync(() => {
  throw new Error('hello');
}).inspectErrSync((err) => console.log(err.message)); // expected "hello" and not ""
```
Codesandbox:
https://codesandbox.io/s/result-bug-6skhyt?file=/src/index.ts

**Comment by hazae41** [comment]
I have two solutions for you:
- a function 'catchSync' that catches without wrapping and returns ´Err<unknown>'
- mirror 'message' in 'Catched' from its cause, but I don't like this one very much
